FROM python:3.11-slim as build-flask
WORKDIR /app/backend

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn
COPY backend .

FROM build-flask as final
EXPOSE 8000
CMD ["python", "app.py"]